name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # or 'master' or whatever your main branch is

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload to S3
        run: |
          zip -r app.zip target/*.jar
          aws s3 cp app.zip s3://${{ secrets.S3_BUCKET }}/app.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name ${{ secrets.APPLICATION_NAME }} \
            --version-label deployment ${{ github.run_number }} \
            --source-bundle S3Bucket=${{ secrets.S3_BUCKET }},S3Key=app.zip

          aws elasticbeanstalk update-environment \
            --environment-name ${{ secrets.ENVIRONMENT_NAME }} \
            --version-label deployment ${{ github.run_number }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
